# Generated by Django 5.2.6 on 2026-03-18 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonafideCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=30, unique=True)),
                ('purpose', models.CharField(choices=[('bank_loan', 'Bank Loan'), ('scholarship', 'Scholarship'), ('passport', 'Passport'), ('visa', 'Visa'), ('employment', 'Employment'), ('higher_study', 'Higher Study Admission'), ('railway_concession', 'Railway Concession'), ('general', 'General Purpose'), ('other', 'Other')], default='general', max_length=30)),
                ('custom_purpose', models.CharField(blank=True, max_length=200)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('additional_text', models.TextField(blank=True, help_text='Any additional information to include in the certificate')),
                ('is_valid', models.BooleanField(default=True)),
                ('downloaded_count', models.IntegerField(default=0)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bonafides', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonafides', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='LeavingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=30, unique=True)),
                ('leaving_date', models.DateField()),
                ('reason', models.TextField()),
                ('last_exam', models.CharField(blank=True, max_length=100)),
                ('conduct', models.CharField(default='Good', max_length=50)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaving_certs', to='students.student')),
            ],
        ),
    ]
